services:
  main:
    image: chat-system/main
    build: 
      context: ./
      dockerfile: Dockerfile
    ports:
      - "2614:80"
  
  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: my-secret
    volumes:
      - pgdata:/var/lib/posgresql/data

volumes:
  pgdata: